select 
cast(O_ORDERKEY as NUMBER) as O_ORDERKEY,
cast(O_CUSTKEY as NUMBER) as O_CUSTKEY,
cast(O_ORDERSTATUS as VARCHAR) as O_ORDERSTATUS,
cast(O_TOTALPRICE as NUMBER) as O_TOTALPRICE,
cast(O_ORDERDATE as DATE) as O_ORDERDATE,
cast(O_ORDERPRIORITY as VARCHAR) as O_ORDERPRIORITY,
cast(O_CLERK as VARCHAR) as O_CLERK,
cast(O_SHIPPRIORITY as NUMBER) as O_SHIPPRIORITY,
cast(O_COMMENT as VARCHAR) as O_COMMENT,
cast(CUR_TIMESTAMP as TIMESTAMP_LTZ) as CUR_TIMESTAMP

from {{ ref('orders_rslt') }}