select 
cast(INGESTION_UNIQUE_KEY as VARCHAR) INGESTION_UNIQUE_KEY,
cast(INGESTION_TYPE as VARCHAR) INGESTION_TYPE,
cast(INGESTION_METADATA as VARCHAR) INGESTION_METADATA,
cast(INGESTION_TIMESTAMP as TIMESTAMP) INGESTION_TIMESTAMP,
cast(I_ORDER_ID as VARCHAR) I_ORDER_ID,
cast(T_ORDER_STATUS as VARCHAR) T_ORDER_STATUS,
cast(T_ORDER_SUMMARY as VARCHAR) T_ORDER_SUMMARY
from 
{{ ref('orders_datatype_test_src') }}