select 
INGESTION_UNIQUE_KEY,
	INGESTION_TYPE,
	INGESTION_METADATA ,
	INGESTION_TIMESTAMP ,
	I_ORDER_ID,
	T_ORDER_STATUS ,
	T_ORDER_SUMMARY
 from DBT_DEMO_PROJECT.RAW.ORDERS
 where ingestion_type = 'Type 789'